### ISSUE TITLE
Feature request: different geometry for pages following the first

### ISSUE THREAD

**Issue by Andreacroci** [LaTeX-Package-Repositories/geometry#13]
### Issue with current situation
tex.stackexchange.com is full of questions regarding the interplay of _geometry_ with _fancyhdr_. When you want a fancy header on the first page and no header on the following pages, you are forced to set the \headeight, which then will be used in the following pages too, leaving a lot of blank space on top. The typical suggestion in order to overcome this is to make the header of the first page part of the text itself, instead of putting it in a fancy header. This works fine, but it has the following problem: normally you want a header to be close to the top of the page (say 1cm or so) and you thus have to set the top margin as such. On the other pages, however, this top margin would be too small and maybe something more like 2-3cm would be more appropriate. In order to change it with a \newgeometry, you need to know exactly where your page ends.

### Request
It is obviously possible to solve this problem with some hooks, but it would be nice if the _geometry_ package would have a command like \firstpagegeometry which applies only to the first page, automatically calculating where it ends and adjusting it as text get edited, and reverts to the preamble geometry on the following page.
For that matter, and more in general, it would be nice if a command _\newgeometry{}_ were working like a _\thispagestyle{}_, not immediately breaking the page, but applying to the current "natural" page.

@davidcarlisle I know you mentioned that you don't know if you have permission to modify this package, but are you at least in touch with the author or should we contact him directly when we have a feature request like this?

**Comment by davidcarlisle** [comment]
It isn't clear why you need to set the top margin differently for the first page.  you can simply use

 `\vspace{whatever is needed} first line of text`

for the more general request `\newgeometry` can only really work at a forced page break, you could potentially change vertical parameters at a natural page but you can not change horizontal dimensions at an automatic page break.

**Comment by Andreacroci** [comment]
OK, the last time I tried with a `tabular` as header, adding a (negative) `\vspace{}` before the table didn't work. But that might be due to other settings in my specific document: I'll have to check again into that.

I guess we can consider this issue closed for the time being.
