### ISSUE TITLE
unexpected result with \newgeometry in curly brackets

### ISSUE THREAD

**Issue by mathqjye** [LaTeX-Package-Repositories/geometry#14]
Hi, David.  I seems to find a bug. The MWE is as follows:

```TeX
\documentclass{article}
\usepackage[paperwidth=3in,paperheight=3in]{geometry}
\begin{document}
First page
\clearpage
{
    \newgeometry{left=1in,bottom=1in}
    Second page
    \clearpage
}
Third page
\clearpage
Fourth page
\end{document}
``` 
![QQ截图20220417105045](https://user-images.githubusercontent.com/35413238/163698196-8d3ae55c-c2e3-4c18-ad23-12720350a000.png)

As you can see, the position of the footer in Page 3 is not corrected and the others are corrected.

By reading the document of the geometry package, I have known that I should code as follows and the result is corrected. But I still curious why the previous code leads to the unexpected result. Thanks.
```TeX
\documentclass{article}
\usepackage[paperwidth=3in,paperheight=3in]{geometry}
\begin{document}
First page
\clearpage
\newgeometry{left=1in,bottom=1in}
Second page
\clearpage
\restoregeometry
Third page
\clearpage
Fourth page
\end{document}
```

**Comment by davidcarlisle** [comment]
`\newgeometry` is making settings in the pdf back end to set the page size (as well as TeX-level settings) TeX grouping doesn't really make sense at that level and the back end settings are not restored at the end of the group, you need an explicit restore.
