### ISSUE TITLE
"`\end occurred when \ifx was incomplete`" in geometry options

### ISSUE THREAD

**Issue by niruvt** [LaTeX-Package-Repositories/geometry#22]
```
\documentclass{article}
\newif\iffoo
\footrue
\usepackage[%
  \iffoo
    paperwidth           = {5in}%
  \fi
]{geometry}

\begin{document}
foo
\end{document}
```

**Comment by josephwright** [comment]
Conditionals inside keyvals are not supported: keyval processors do not expand input so the `\iffoo` is split from the `\fi` leading to the error.

**Comment by davidcarlisle** [comment]
As @josephwright  said. 

I can't recommend mixing latex options with tex  primitves in this way, but if you need such a syntax you need to expand out the conditionals before processing the options, so something like

```
\documentclass{article}
\newif\iffoo
\footrue
\expanded{\noexpand\usepackage[%
  \iffoo
    paperwidth           = {5in}%
  \fi
]{geometry}}

\begin{document}
foo
\end{document}
```

**Comment by niruvt** [comment]
Thanks @josephwright and @davidcarlisle!

I realized that I made the same mistake [again](https://github.com/latex3/unicode-math/issues/639).

But now, I would like to raise a question. What is theoretically wrong in the syntax I have used? 1. How can and 2. why should it be expected from authors to know that key-value interface doesn't support expansion? I made this mistake twice. Agreed that there are ways to handle this as shown by both of you, but it is a requirement/restriction that nobody would logically expect. I got a solution because I thought it was a problem, I reported it and you kindly replied with alternative ways, but what about general users who don't pay careful attention to the log, warnings etc.? Considering the increasing popularity of key-values, I think, as a language that endorses "logical structure", LaTeX should support this syntax. I understand the maintenance load, but if you agree with this and are ready to make this available, I can work on this and create PRs for some popular packages at least. Let me know what you think.

**Comment by davidcarlisle** [comment]
To be honest I don't see why you would expect any users to expect thus to work. No keyval system would do that as far as I know. 

If the argument was expanded before splitting on commas and = you wouldn't be able to have things like font=\bfseries. As the value would be expanded at the wrong time. It is well  documented that the key is the part before = and the value is the part after =, to the next comma.

**Comment by josephwright** [comment]
@niruvt In addition to what @davidcarlisle says, _LaTeX_ documentation for end users doesn't mention expansion at all; moreover, `\if...` is TeX not LaTeX syntax. As such, the question is more why one would expect this to work based on LaTeX docs at all.

At a technical level, we have looked at expansion of key _names_ leaving values alone. This is tricky to do, has poor performance and doesn't really lead to a clearer situation. For example, here, you have `\fi` in the 'value' part, so it still doesn't help. As such, we ruled it out.

**Comment by niruvt** [comment]
> To be honest I don't see why you would expect any users to expect this to work. No keyval system would do that as far as I know.

Sorry, I had some confusion, after testing a bit, I have reached the same MWE again:

```latex
\documentclass{article}
\usepackage{xcolor}
\newif\iffoo
\footrue
\usepackage{unicode-math}
\setmainfont[%
  \iffoo
    Color           = {red}%
  \fi
]{CharisSIL-Regular.ttf}
\setmathfont[%
  % \iffoo% Fails if uncommented
    Color           = {red}%
  % \fi
]{XITSMath-Regular.otf}

\begin{document}
abcd $123$
\end{document}
```

This is a case where two similar commands have differences in expanding their optional arguments. Which parser does `fontspec` use? Agreed that this does not work with the optional argument of `\usepackage` command. That was my bad.

> If the argument was expanded before splitting on commas and = you wouldn't be able to have things like font=\bfseries. As the value would be expanded at the wrong time. It is well documented that the key is the part before = and the value is the part after =, to the next comma.

If we have control over the usage of `=`, why can't we have something like:

```latex
\usepackage[%
  % expand everything till an = is reached
  \iffoo
    someopt
    = % stop expansion till a , is reached
    \bfseries,% start expansion
  \fi
  anotheroption
]{somepkg}
```

@josephwright,

> LaTeX documentation for end users doesn't mention expansion at all

Sure, I am not expecting them to know expansion either. I am just expecting a different (and uniform) working of the optional argument processing (cf. `fontspec` vs. `unicode-math` example above).

> moreover, \if... is TeX not LaTeX syntax

Oh! 😮

Despite theoretically being quite straight forward (LaTeX is not TeX), this kinda shocked me, because this distinction was never so strict in my mind. Mixed code that uses both of these is so omnipresent that it never occurred to me that `\if`-syntax isn't LaTeX. But now since you mentioned this, what should one do when they need to use conditionals in _LaTeX_?

**Comment by niruvt** [comment]
@josephwright I think my main point is loading options conditionally is not _that_ illegitimate of a requirement. I only knew about `\if`-type macros, so I used them. If available, I am okay with shifting to new LaTeX-y versions of `\if` too, but are you hinting that user-side LaTeX (as opposed to LaTeX3) has no intention of supporting conditionals at all?

**Comment by niruvt** [comment]
> For example, here, you have \fi in the 'value' part, so it still doesn't help. As such, we ruled it out.

Oh, yes. Correct. I get the problem now.

Quite tricky, indeed.

Thanks for the clarification.

**Comment by davidcarlisle** [comment]
There are lots of user facing conditional LaTeX commands `\IfBooleanTF{foo}{yes}{no}` for example. Also while they are definitely a tex primitive and not official latex syntax tex primitive conditionals will also work `\iffoo....\fi`  but you can't use conditionals (of any kind) in arbitrary places mixed with other syntax. A keyval option is a kind of assignment, your suggested use is very close to

```
\newcommand{\iffoo \this\else\that\fi}{hmm}
```

and that doesn't work either. You need to pull the conditional outside


```
\iffoo
\newcommand{\this}{hmm}
\else
\newcommand{\that}{hmm}
\fi
```

and the same is true of the keyval setting (in general)

**Comment by niruvt** [comment]
@davidcarlisle got it. The parallel example you give is definitely comparable. I get the complexity now. Thanks for clarifying.

**Comment by Skillmon** [comment]
Regarding your question which system `fontspec` uses: `l3keys`, but it uses `x` expansion at multiple points in its code. Still I'd not always expect it to do that expansion for me.
